/*
QueryAPI file
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NHibernate;
using NHibernate.Cfg;
using Entity;

namespace Dao
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	public class BookQuery
	{

		/// <summary>
		/// </summary>
		public bool InsertAPI( Book  element)
		{
			Configuration cfg = new Configuration().Configure();
			ISession session = cfg.BuildSessionFactory().OpenSession();
			ITransaction transaction = session.BeginTransaction();
			try
			{
				session.Save(element);
				transaction.Commit();
				return true;
			}
			catch (Exception e)
			{
				transaction.Rollback();
				return false;
			}
			finally
			{
				session.Close();
			}
		}		
	
		/// <summary>
		/// </summary>
		public IList<Book> GetInfoAPI( int iStart, int iCount)
		{
			Configuration cfg = new Configuration().Configure();
			ISession session = cfg.BuildSessionFactory().OpenSession();
			ICriteria crit = session.CreateCriteria(typeof(Book));
			crit.SetFirstResult(iStart);
			crit.SetMaxResults( iCount );
			IList<Book> list = crit.List<Book>();
			return list;
		}		
	
		/// <summary>
		/// </summary>
		public IList<Book> GetAllInfoAPI()
		{
			Configuration cfg = new Configuration().Configure();
			ISession session = cfg.BuildSessionFactory().OpenSession();
			IList<Book> list = session.CreateQuery(" from Book ").List<Book>();
			return list;
		}		
	
		/// <summary>
		/// </summary>
		public bool UpdateAPI( Book  element)
		{
			Configuration cfg = new Configuration().Configure();
			ISession session = cfg.BuildSessionFactory().OpenSession();
			ITransaction transaction = session.BeginTransaction();
			try
			{
				session.Update(element);
				transaction.Commit();
				return true;
			}
			catch (Exception e)
			{
				transaction.Rollback();
				return false;
			}
			finally
			{
				session.Close();
			}
		}		
	
		/// <summary>
		/// </summary>
		public bool DeleteAPI( Book  element)
		{
			Configuration cfg = new Configuration().Configure();
			ISession session = cfg.BuildSessionFactory().OpenSession();
			ITransaction transaction = session.BeginTransaction();
			try
			{
				session.Delete(element);
				transaction.Commit();
				return true;
			}
			catch (Exception e)
			{
				transaction.Rollback();
				return false;
			}
			finally
			{
				session.Close();
			}
		}		
	
		/// <summary>
		/// </summary>
		public Book GetInfoByIdAPI(int elementID)
		{
			Configuration cfg = new Configuration().Configure();
			ISession session = cfg.BuildSessionFactory().OpenSession();
			return session.Get<Book>(elementID);
		}		
	
		/// <summary>
		/// </summary>
		public IList<object[]> CreateQueryAPI(string strQuery)
		{
			Configuration cfg = new Configuration().Configure();
			ISession session = cfg.BuildSessionFactory().OpenSession();
			IList<object[]> list = session.CreateQuery(strQuery).List<object[]>();
			return list;
		}
		
	}
}
